version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: [ "python", "manage.py", "test" ]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
