version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:8080"
    depends_on:
      - web
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  web2:
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  web3:
    build:
      context: .
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  web4:
    build:
      context: .
    ports:
      - "8003:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
